featurecat/lizzie

src/wagner/stephanie/lizzie/gui/BoardRenderer.java
src/wagner/stephanie/lizzie/rules/Board.java
src/wagner/stephanie/lizzie/rules/BoardHistoryList.java

Implements the feature request of #52. The next move of the game (if any) is circled in black or white, depending on the player, slightly outside the red circle of Leela Zero's top move so that they are visible independently. See if you like it.

Highlight next move

---

src/wagner/stephanie/lizzie/rules/SGFParser.java

Fixes a bug where parentheses inside tags (notably comments) would cause the SGFParser to exit early.

Don't react to parentheses inside tags

---

src/wagner/stephanie/lizzie/rules/Board.java
src/wagner/stephanie/lizzie/rules/BoardHistoryList.java
src/wagner/stephanie/lizzie/rules/BoardHistoryNode.java
src/wagner/stephanie/lizzie/rules/SGFParser.java

This partially implements @ProLeela's request in issue #32.
From a user standpoint, Lizzie now remembers the entire variation tree that has been explored. Right-arrow always chooses the original move played in the current position (this is the move from the SGF file if it exists), and that is the move displayed with a black or white outline. This means that you can now explore a variation, left-arrow back to the main trunk, and then continue with the loaded game (previously, the rest of the loaded game would be blown away).
From a coder standpoint, this code should probably be examined a little more closely than my other pull requests. I'm not a Java programmer and don't know whether my use of `ArrayList`s to store child `BoardHistoryNode`s is inefficient with respect to speed or memory. …

Remember variation tree, easily return to main trunk

---

src/wagner/stephanie/lizzie/rules/SGFParser.java

Implements one request from issue #32, which I wanted as well: when an SGF file is loaded, we start at the beginning of the game, not the end.

Start at beginning of game after loading SGF file

---

src/wagner/stephanie/lizzie/rules/SGFParser.java

I encountered a NullPointerException when I tried to save an SGF file.
The reason was that LeeLa played a pass move.
Pass moves should be in format ";B[tt]" according to the SGF standard.
I changed a couple of things to this method:
1) a try-finally mechanism assures that the file is always properly closed.
2) if no color is found, there is no longer a "return" statement, but a "continue" statement.
3) support for the pass moves.
4) some cosmetics: line-breaks/comments/eliminated a StringBuilder.
Everything is tested and works great :).

add support for pass moves.

---

src/main/java/wagner/stephanie/lizzie/analysis/Branch.java
src/main/java/wagner/stephanie/lizzie/analysis/Leelaz.java
src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java
src/main/java/wagner/stephanie/lizzie/gui/WinrateGraph.java
src/main/java/wagner/stephanie/lizzie/rules/Board.java
src/main/java/wagner/stephanie/lizzie/rules/BoardData.java
src/main/java/wagner/stephanie/lizzie/rules/BoardHistoryList.java

I added a winrate with bars that show black and whites winning chance, and more importantly, the change in this for the last move. This makes it easier to spot when you make a mistake (large negative change in win chance) and how "big" the mistake was. I considered adding color coding (orange for medium mistake, red for big mistake), but didn't add this now.
I didn't ask or make a feature request first, but I think this is useful.

Display winrate in separate box when in pondering mode.

---

src/main/java/wagner/stephanie/lizzie/gui/BoardRenderer.java

Lizzie now can show the coordinates to help place or record moves by pressing the shortcut "C". But I find that if a stone was placed on the edge of the board(that is, Row 1 or 19, or Column A or T), it would hide the coordinate texts, because the coordinate texts are too close to the board lines.
I managed to find a simple and quick solution for this: just increased the value of `BoardRenderer.MARGIN` from `0.03` to `0.06`, so that there would be enough room between the coordinate texts and the stones and the stones would not hide the texts no longer.

Widen the margin of board so that the stones will not hide coordinates

---

src/main/java/wagner/stephanie/lizzie/gui/Input.java
src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java
src/main/java/wagner/stephanie/lizzie/rules/SGFParser.java

It is a very nice feature of Lizzie to load SGF from a file and save SGF to a file. But sometimes we would like to import/export a game from/to clipboard. For example, someone may paste the SGF contents of a game to a post and we are interested to the game, or we just want to copy/paste games from/to another game editor. I implemented this feature that allows copies from/pastes to clipboard.
Two new hot keys are added to support the feature, that is, Alt-C and Alt-V, to copy and paste. Because CTRL is already used in other functions. I resort to use Alt key.

Implemented Copy SGF to clipboard and paste SGF from clipboard

---

src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java
src/main/java/wagner/stephanie/lizzie/gui/VariationTree.java
src/main/java/wagner/stephanie/lizzie/rules/BoardHistoryList.java
src/main/java/wagner/stephanie/lizzie/rules/BoardHistoryNode.java

I've added a suggestion for showing the variation tree. The algorithm for getting the layout is a bit tricky (might be possible to simplify, this is what I came up with (started fiddling with it yesterday)), so there might still be bugs that get some lines crossed. Let me know if you observe this (a screen capture of the tree is most useful in that scenario).
I've just put the tree on the right side for now. There is no animations or anything, and just 2D drawing, but it's a start. If this would be better to draw a different way (inside some frames/panel or using some library or what not), please feel free to change it (and anything else of course), that should be trivial. It is the layout algorithm that requires a bit of thinking.
In time, the nodes should be clickable, we could see if …

Added display of variation tree

---

src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java
src/main/resources/l10n/DisplayStrings.properties
src/main/resources/l10n/DisplayStrings_zh_CN.properties

This PR addresses #79. It changed some codes to use `ResourceBundle` in Java to display localized strings.
Before the change, a piece of code may display a hard-coded string:
```
displayString("Some hard coded string");
```
After the change, the code will use resource bundle to get localized string:
```
displayString(resourceBundle.getString("The.key.of.the.string"));
```
And in the base translation file:
```
The.key.of.the.string=Some hard coded string
```
In localized translation file:
```
The.key.of.the.string=......(Localized translations)
```
I made simplifiled Chinese translations too. But there's no translations of other languages. So Lizzie will display Chinese in a system with locale set to zh_CN, and display English by default in all other systems. If someone could help …

Added localization support and Chinese translations

---

src/main/java/wagner/stephanie/lizzie/gui/Input.java
src/main/java/wagner/stephanie/lizzie/gui/VariationTree.java
src/main/java/wagner/stephanie/lizzie/rules/Board.java
src/main/java/wagner/stephanie/lizzie/rules/BoardHistoryList.java
src/main/java/wagner/stephanie/lizzie/rules/BoardHistoryNode.java

I've added support for navigating between variations using arrow keys. Basically, you move between moves with same move number.
There are two design choices I made that is good to be aware of.
- When moving to the right (variations), you are only allowed to move to variations that start on the same move on the main trunk. No such limitations when you're moving the other way. Possible to allow to move to any variation, but then you have to search the entire tree.
- If a variation is longer than the main branch (trunk), you are still allowed to move back to trunk
Disclaimer: There might be a more elegant way to do this (felt like a long complicated algorithm for something that "simple"), but I haven't spent any time looking for better solutions. Anyway, it works (I hope).

Navigate variation

---

src/main/java/wagner/stephanie/lizzie/Config.java

One last flag to make it easy to run Lizzie the way I (and presumably some others) like. `show-leelaz-variation` controls whether Leela Zero's principal variation is displayed. Defaults to true (current behavior).

Property to toggle Leela Zero variation display

---

src/main/java/wagner/stephanie/lizzie/Config.java

Fixes #108. We create a list of default properties, and if the user's config file is missing any of them (or if they don't have a config file at all), we add the default key-value pairs and save the new config out.
I also added config properties for all the options that can currently be toggled in the UI for completeness, now that it's trivial.

Default properties

---

src/main/java/wagner/stephanie/lizzie/analysis/Branch.java
src/main/java/wagner/stephanie/lizzie/analysis/Leelaz.java
src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java
src/main/java/wagner/stephanie/lizzie/gui/WinrateGraph.java
src/main/java/wagner/stephanie/lizzie/rules/Board.java
src/main/java/wagner/stephanie/lizzie/rules/BoardData.java

Fixes #104. `BoardData` now includes the number of Leela Zero playouts for each node, and node stats are updated only when visited more than before. The winrate graph draws lines only where nodes have been visited. This means:
- You don't see long flat lines on the win graph where there is missing data (just loaded an SGF file, or quickly arrowed through part of it)
- Quickly arrowing through nodes doesn't reset their winrate, which used to cause more long flat lines.

Only display visited nodes on winrate graph

---

src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java

Fixes #134.
When there's nothing useful to display for the winrate bar, don't display anything.

Don't display nonexistent info in winrate bar

---

src/main/java/wagner/stephanie/lizzie/Config.java
src/main/java/wagner/stephanie/lizzie/gui/BoardRenderer.java
src/main/java/wagner/stephanie/lizzie/gui/Input.java

When the board is too complicated with many best moves, I want to hide
variations etc. temporally.  This hotkey (z) works while it is held
down like "x" key.  So I selected "z", the next key in the keyboard.  I
am not sure which key is suitable, though.

Hotkey to hide variations etc. temporally

---

src/main/java/wagner/stephanie/lizzie/gui/Input.java
src/main/java/wagner/stephanie/lizzie/rules/Board.java

Thanks to the recent Del key feature, I can easily try various moves
with temporal branches.  To make it easier, I added a new hotkey
(shift + up arrow) to go back quickly to the top of the current
branch.  It stops at the child position of the junction position so
that I can delete the current branch conveniently with this key and
Del key.  When I really want to go to the junction position, I simply
hit this key twice.

Hotkey to go to the top position of the current branch

---

src/main/java/wagner/stephanie/lizzie/gui/BoardRenderer.java
src/main/java/wagner/stephanie/lizzie/gui/Input.java
src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java

I often want to watch continuations of variations suggested by leelaz
because I cannot understand the reason why their winrates are so
high/low.  I added a hotkey to do it quickly on my slow machine
without GPU.  This hotkey (,) puts stones as the currently displayed
variation, and I can conveniently watch leelaz's prediction further.
I am not sure which key is suitable for this feature.

Hotkey to play the displayed variation

---

src/main/java/wagner/stephanie/lizzie/gui/BoardRenderer.java

This makes it no longer unnecessarily hard to spot the best move by its red ring and doesn't lose any visual information. Plainer change than what was proposed in #84.

Show best move in cyan.

---

src/main/java/wagner/stephanie/lizzie/gui/Input.java

I use Control key to move the window focus, e.g. Ctrl+Tab to raise
another window, Ctrl+F3 to go to the workspace 3, etc.  When I use
these shortcuts and return to Lizzie later, it is still in "Ctrl"
state and Up/Down arrow keys cause 10 moves without this commit.
Steps to reproduce the problem:
(1) Start Lizzie and put some stones.
(2) Holding Ctrl key in Lizzie window, move the focus to another window.
(3) Release Ctrl key.
(4) Click Lizzie window to move the focus back.
(5) Hit Up arrow key.
I expect a single undo in (5). But I get 10 undos instead.

Fix Ctrl key problem when the window focus is moved

---

README.md
src/main/java/wagner/stephanie/lizzie/analysis/Leelaz.java
src/main/java/wagner/stephanie/lizzie/analysis/MoveData.java

I implemented #178 as a failsafe mode for both Leela 0.11.0 and the
original Leela Zero without modification.  See the bottom of README.md
to use Leela 0.11.0.
Though "parseLineNormal" and "parseLineFailSafe" have many common
lines, I dare to copy them naively because "parseLineNormal" will be
rewritten for the official pondering output by the original Leela zero
in near future.
(cf.) https://github.com/gcp/leela-zero/pull/1242

Failsafe mode for incompatible Leela

---

src/main/java/wagner/stephanie/lizzie/gui/BoardRenderer.java
src/main/java/wagner/stephanie/lizzie/rules/Board.java
src/main/java/wagner/stephanie/lizzie/rules/BoardHistoryList.java

The first commit fixes #154 (Handicap stones are not removed).
The second commit fixes another related issue:
1. Start Lizzie.
2. Hit "n" key (new game)
3. Input "4" on Handicap field and click "OK".
I expect four black stones appear on the board immediately.
But the board is empty until leelaz puts the first white stone.
We have three problems about handicap stones.
1. Data in the root node is never cleared.
2. Zobrist hash is not updated for handicap stones.
3. Same Zobrist object is owned jointly by a node and Boardrenderer's cache. Even if we update zhash of a node, Boardrenderer's cache is also updated and they are still "equal".

Fix #154 (Handicap stones are not removed)

---

src/main/java/wagner/stephanie/lizzie/gui/WinrateGraph.java

I occasionally miss the current position in the winrate graph.  How
about drawing a vertical line at the current move in the graph?  It is
consistent to the UI of mouse-hovering and clicking on the graph.

Draw vertical line at current move in winrate graph

---

src/main/java/wagner/stephanie/lizzie/rules/SGFParser.java

My favorite SGF tool (xmgt) uses the long format SGF by default.
We need only a single line code to support it.

Support long format SGF

---

src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java
src/main/java/wagner/stephanie/lizzie/rules/Board.java

1. Start Lizzie
2. Hit "c" key (coordinates on)
3. Hit Ctrl-c key (copy SGF)
4. Click D16 (black)
5. Hit Ctrl-v key (paste SGF)
Then the board is empty. But candidate moves of leelaz appear asymmetrically
(no candidate around D16 as if we had an invisible black stone there).
This commit fixes it by sending "clear_board" to leelaz before loading/pasting SGF.

Clear leelaz's board before loading/pasting SGF

---

src/main/java/wagner/stephanie/lizzie/rules/Board.java

Lizzie ignores DEL key at the root node currently.  With this patch,
Lizzie deletes everything instead.
My real aim of this patch is giving users an intuitive way to
delete handicap stones after a handicapped game.  Otherwise, users
have to start a new game with no handicap to delete previous handicap
stones.
This patch also gives a way to recover from #201.

Empty the board by DEL key at the root node

---

src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java
src/main/java/wagner/stephanie/lizzie/rules/Board.java
src/main/java/wagner/stephanie/lizzie/rules/BoardHistoryList.java

When we are on a variation (length N) that is shorter than the main
trunk, we have no action for a click in the winrate graph if the
clicked point corresponds to a move > N.  I prefer showing the
corresponding move in the main trunk instead.

Fix mouse-click behavior of winrate graph

---

src/main/java/wagner/stephanie/lizzie/gui/Input.java
src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java

If we type Up/Down arrow keys while the mouse pointer is in the
winrate graph, their actions are canceled and the previous board is
restored when the pointer leaves the graph.  I expect that such
"intentional" actions should be permanent, whereas mouse-hover actions
are temporal.

Don't cancel hotkey actions on winrate graph

---

src/main/java/wagner/stephanie/lizzie/gui/WinrateGraph.java

We can jump to the Nth move quickly by clicking the winrate graph
if we show the move number there.

Show move number in winrate graph

---

src/main/java/wagner/stephanie/lizzie/gui/BoardRenderer.java
src/main/java/wagner/stephanie/lizzie/gui/Input.java
src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java

(First commit)
This patch enhances the behavior of Z key (show raw board).  Holding Z
key on a suggested move of leelaz, we see only the move numbers
(without stones) of the variation.  Up arrow key hides these move
numbers, and Down arrow key shows stones one by one.  I think this is
useful for watching complicated variations.
(Second commit)
Shift-Z toggles showNextMoves, showBestMoves, and showBranch at once.
I intend to use Lizzie as a training tool with this no-hint view and #222 (Play the best move).

Enhance Z key feature (show raw board)

---

src/main/java/wagner/stephanie/lizzie/analysis/Leelaz.java

1. Make the original leela-zero-0.14 ready.
2. Start Lizzie (in failsafe mode)
3. Hit Enter key
Then I get an error.
> time_settings 0 2 1
> genmove B
> time_left b 0 0
49 non leaf nodes, 1.47 average children
73 visits, 26227 nodes
= Leela Zero
Exception in thread "Thread-3" java.lang.NumberFormatException: For input string: "eela Zero"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:580)
at java.lang.Integer.parseInt(Integer.java:615)
at wagner.stephanie.lizzie.rules.Board.convertNameToCoordinates(Board.java:70)
at wagner.stephanie.lizzie.rules.Board.place(Board.java:271)
at wagner.stephanie.lizzie.analysis.Leelaz.parseLineFailSafe(Leelaz.java:315)
at wagner.stephanie.lizzie.analysis.Leelaz.parseLine(Leelaz.java: …

Fix NumberFormatException at Enter key in failsafe mode

---

src/main/java/wagner/stephanie/lizzie/rules/Board.java

Auto-analysis is often aborted on my slow machine (every 3-10 moves).
How about ignoring empty notifications instead of aborting auto-analysis?

Don't abort auto-analysis. Ignore empty notifications instead.

---

src/main/java/wagner/stephanie/lizzie/rules/Board.java

I overlooked a side effect of #227.

Fix: auto-analysis did not stop if the last two moves are "pass"

---

src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java

Please try "w" key and watch the font size in the captured stones panel.
"setFont" was missing in "drawCaptured".

Fix: font size of drawCaptured was changed when winrate graph was hidden

---

src/main/java/wagner/stephanie/lizzie/gui/BoardRenderer.java

As the variant of #84 I've settled on, this will give the most visited child move a red ring if it does not also have the highest average win rate and hands out a blue ring in the inverse case.
Although I personally found this useful to investigate whether these two metrics always eventually agree on the best move, I can totally understand it if this doesn't get merged because it's too much in terms of visual information.

Return of the special rings

---

src/main/java/wagner/stephanie/lizzie/Config.java
src/main/java/wagner/stephanie/lizzie/gui/BoardRenderer.java
src/main/java/wagner/stephanie/lizzie/gui/Input.java
src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java
src/main/java/wagner/stephanie/lizzie/gui/VariationTree.java

I feel that zero-click UI is the key invention of Lizzie.  It makes
analyses of games much fun.  I had never imagined that the difference
between 1-click and 0-click is so large until I experienced it by
myself.
Along this direction, I added a subboard that always shows the
principal variation.  We do not need even mouse-hovering to see it.
It is hidden by shift-Z key (no-hint view in #223) and enlarged by
mouse click on it.  I also added "show-subboard" and "large-subboard"
into lizzie.properties.
Of course this feature is entirely redundant.  But I think that "can
do" and "can do with no action" is different.
Though this PR is rather large, half of changed lines are mere layout
parameters.

Add subboard that always shows the principal variation

---

src/main/java/wagner/stephanie/lizzie/gui/BoardRenderer.java

This reverts commit f89e83619e5aabf139107af84f9f776d13084093.
I intentionally used non-fancy style for subboard because it is "sub".
But I know my design sense is unreliable.  This patch reverts the
commit f89e836 (Use non-fancy style for subboard) and applies the same
style for both boards.  Is it better?  Either is ok for me.

Revert "Use non-fancy style for subboard"

---

src/main/java/wagner/stephanie/lizzie/rules/SGFParser.java

These commits fix problems for SGF from http://eidogo.com/#32R1CLyop
(1) Read
C[foo [3d\]: ...]
as "foo [3d]: ..."
(2) Update window title and rewind to game start after reading SGF
I omitted further exceptional rules in the SGF specification.
See "3.2. Text" in https://www.red-bean.com/sgf/sgf4.html for example.

Fix SGF issues (escaping, MultiGo postprocess)

---

src/main/java/wagner/stephanie/lizzie/rules/SGFParser.java

My old *.sgf have mail headers before SGF.
It is good to accept loose SGFs as far as we can do that easily, I think.

Ignore garbage texts around SGF

---

src/main/java/wagner/stephanie/lizzie/gui/WinrateGraph.java

Click/drag was ignored if it was near the margin of winrate graph.

Improve behavior of click/drag near margin of winrate graph

---

src/main/java/wagner/stephanie/lizzie/Config.java
src/main/java/wagner/stephanie/lizzie/analysis/Leelaz.java
src/main/java/wagner/stephanie/lizzie/gui/BoardRenderer.java
src/main/java/wagner/stephanie/lizzie/rules/Board.java

This PR addresses #152 . The issue only mentions 9x9 board support, but as far as I know, someone has started training 13x13 weights. Although the current weight is very weak, we can still expect a strong weight in a few months(I guess ?). So that I add 13x13 support too.
The code changes of small size boards are fairly simple. The key is the constant `Board.BOARD_SIZE`. There are a few places in class `BoardRenderer` that used hard-coded `19` as the board size. And all of the places have been modified to use the constant. Next, if we just change the board size and hard-code the number `9`, it should work. But it should be better to let the user configure the board size. So I added the config item `board-size` in `ui` category. To prevent some curious users spoiling the config item(e.g. …

Preliminary support for 9x9 and 13x13 boards.

---

src/main/java/featurecat/lizzie/analysis/Leelaz.java

This patch fixes #251 and another issue that only 3 stones appear when handicap = 4.

Fix #251 (Handicap stones do not appear)

---

src/main/java/featurecat/lizzie/rules/Board.java
src/main/java/featurecat/lizzie/rules/BoardHistoryList.java
src/main/java/featurecat/lizzie/rules/SGFParser.java

These commits fix the following issues in SGF reader.
1. GameInfo was lost for handicapped SGF.
2. Reading failed for SGF with empty "KM[]".
example
http://gokifu.net/t2.php?s=7001484524613847

Fix issues on komi and handicap in SGF reader

---

src/main/java/featurecat/lizzie/Lizzie.java
src/main/java/featurecat/lizzie/analysis/Leelaz.java
src/main/resources/l10n/DisplayStrings.properties
src/main/resources/l10n/DisplayStrings_zh_CN.properties

Checks if both leela zero and that network-file/weights are present (and that config.txt is setup correctly), and present an error if not. Should make it easier for user to figure out what is wrong when Lizzie just closes immediately.

Sanity checks

---

src/main/java/featurecat/lizzie/rules/BoardHistoryList.java
src/main/java/featurecat/lizzie/rules/SGFParser.java

1. Start lizzie
2. Hit "c" key (coordinates on)
4. Click D17 (black)
5. Hit UP ARROW key (undo)
6. Hit Ctrl-C (save to clipboard)
Then suggestion appears on the existing stone at D17.  This happens
because saveToStream in SGFParser.java moves head of history as a side
effect without telling it to leelaz.
Though this is not a serious issue by itself, it is problematic for
developing an autosave feature (#140, #263).

Fix: suggestion appears on a existing stone after Ctrl-C

---

src/main/java/featurecat/lizzie/Config.java
src/main/java/featurecat/lizzie/gui/BoardRenderer.java
src/main/java/featurecat/lizzie/gui/Input.java
src/main/java/featurecat/lizzie/gui/LizzieFrame.java

I prefer modest suggestions so that I can imagine the current board
situation without holding "z" key down.  I assigned minor keys
(ctrl-shift-pgup/pgdown) to modify the opacity of suggestions since
we will not use them frequently.

Increase/decrease alpha value by ctrl-shift-pgup/pgdown

---

src/main/java/featurecat/lizzie/gui/BoardRenderer.java

To avoid confusing empty blue circles as seen in #293.

Always show statistics for blue-ringed moves.

---

src/main/java/featurecat/lizzie/analysis/Leelaz.java

"Ctrl-V" takes several minutes on my machine.
It is caused by "lz-analyze" after every "play ..." and "undo".
You may not notice this issue if your machine is fast.
The first patch introduces a command queue and defers sending commands
until leelaz responds to the previous command.
Unnecessary "lz-analyze", that will be stopped immediately by the next command,
is removed from the queue before sending it to leelaz.
I also add the second patch for preventing possible hang-up in unexpected cases
that cannot happen theoretically.
$ git log --oneline | head -n 1
1912f4a Merge pull request #272 from kaorahi/komi_sgf

Fix too slow "End", "Ctrl-V", etc. by omitting unnecessary lz-analyze

---

src/main/java/featurecat/lizzie/analysis/Leelaz.java

I get the below alert dialog at startup without this patch.
Did not find network/weights.
Update config.txt (network-file) or download from Leela Zero homepage
The value of the variable startfolder should be ".". But I get "./leelaz".

Fix "Did not find network/weights"

---

src/main/java/featurecat/lizzie/rules/SGFParser.java

This patch allows whitespace characters between the last two ")"s in the detection of MultiGo SGF.

Fix #296 (MultiGo SGF detection)

---

src/main/resources/l10n/DisplayStrings_RO.properties

Hello,
I created a localization file for the Romanian language. 
However I have a few questions: Has anyone tested localization before? Is it working right now? I compiled the build with the file with Maven on my machine (a fist time for me) and it still displayed the English text.
I am new at contributing on GitHub, so let me know if I made any mistakes.
Thank you,
Mihai

Add Romanian localization

---

pom.xml
src/main/java/featurecat/lizzie/rules/Board.java
src/main/java/featurecat/lizzie/rules/BoardData.java
src/main/java/featurecat/lizzie/rules/BoardHistoryList.java
src/main/java/featurecat/lizzie/rules/SGFParser.java
src/test/java/common/Util.java
src/test/java/featurecat/lizzie/rules/SGFParserTest.java

Closes #350 
Support following features when Read/Write the SGF file:
1. Variations tree
2. AW/AB (Add White)/(Add Black) stone
3. Comment (C tag)

next: Support Read/Write Sgf with Variation, AW/AB & Comment

---

src/main/java/featurecat/lizzie/gui/BoardRenderer.java
src/main/java/featurecat/lizzie/gui/LizzieFrame.java

#361 
1. The change support seamless texture for background and board.
2. Enhance the stone draw quality

next: Support Seamless Texture & Enhance Stone Quality

---

src/main/java/featurecat/lizzie/gui/BoardRenderer.java

The change supports display only last move number that can be specified in the config.txt.
For example, only display last 10 move number:
"ui": {
"only-last-move-number": 10,

next: Support Display Only Last Move Number

---

src/main/java/featurecat/lizzie/rules/Board.java

The y-coordinate as shown doesn't match what is communicated with the engine, although the conversion is consistently wrong in both directions and therefore not normally noticeable.

Fixed inversion of named y-coordinate.

---

src/main/java/featurecat/lizzie/Config.java
src/main/java/featurecat/lizzie/Lizzie.java
src/main/java/featurecat/lizzie/analysis/Leelaz.java
src/main/resources/l10n/DisplayStrings.properties
src/main/resources/l10n/DisplayStrings_zh_CN.properties

Fixes #323 
Don't pointlessly recalculate paths, just take them from the config directly since they've already been calculated by then.
Drop `engine-program` since it's not being used, just take the first element of the split string `engine-command` like we already do for `ProcessBuilder`.

 Fix location checks, and use engine-start-location directly

---

pom.xml
src/main/java/featurecat/lizzie/analysis/Leelaz.java
src/main/java/featurecat/lizzie/analysis/MoveData.java
src/main/java/featurecat/lizzie/rules/Board.java
src/test/java/featurecat/lizzie/analysis/MoveDataTest.java

This PR adds a new parser for what I've called "summary line". Leelaz will systematically output small summaries like the following once it reached the maximum number of visits specified with the `--visit` flag:
```
O4 ->       5 (V: 53.21%) (N: 39.95%) PV: O4 F3 C6 C17
F3 ->       4 (V: 54.48%) (N: 34.51%) PV: F3 F17 E17 F16
```
Parsing this data fixes #362.
This PR also setups JUnit and adds a few tests for the new regular expression.

Fix #362: show best moves after --visit exhaustion

---

src/main/java/featurecat/lizzie/Config.java
src/main/java/featurecat/lizzie/gui/Input.java
src/main/java/featurecat/lizzie/gui/LizzieFrame.java
src/main/java/featurecat/lizzie/gui/VariationTree.java
src/main/java/featurecat/lizzie/rules/BoardHistoryList.java
src/main/resources/l10n/DisplayStrings.properties
src/main/resources/l10n/DisplayStrings_RO.properties
src/main/resources/l10n/DisplayStrings_zh_CN.properties

Closes:    #350 
This pull request based on #364 
1. Support for displaying comments of the sgf files.
Default is close, can press key 'T' to toggle, and add a item 'show-comment' in the config file.
2. Allow use a hidden item 'comment-font-size' in the config to forced specify the comment font size, for example:
"comment-font-size": 20

next: Support display the comment of the SGF file

---

pom.xml
src/main/java/featurecat/benchmark/Stopwatch.java
src/main/java/featurecat/lizzie/Config.java
src/main/java/featurecat/lizzie/Lizzie.java
src/main/java/featurecat/lizzie/Util.java
src/main/java/featurecat/lizzie/analysis/Branch.java
src/main/java/featurecat/lizzie/analysis/GameInfo.java
src/main/java/featurecat/lizzie/analysis/Leelaz.java
src/main/java/featurecat/lizzie/analysis/LeelazListener.java
src/main/java/featurecat/lizzie/analysis/MoveData.java
src/main/java/featurecat/lizzie/gui/BoardRenderer.java
src/main/java/featurecat/lizzie/gui/GameInfoDialog.java
src/main/java/featurecat/lizzie/gui/Input.java
src/main/java/featurecat/lizzie/gui/LizzieFrame.java
src/main/java/featurecat/lizzie/gui/NewGameDialog.java
src/main/java/featurecat/lizzie/gui/VariationTree.java
src/main/java/featurecat/lizzie/gui/WinrateGraph.java
src/main/java/featurecat/lizzie/rules/Board.java
src/main/java/featurecat/lizzie/rules/BoardData.java
src/main/java/featurecat/lizzie/rules/BoardHistoryList.java
src/main/java/featurecat/lizzie/rules/BoardHistoryNode.java
src/main/java/featurecat/lizzie/rules/GIBParser.java
src/main/java/featurecat/lizzie/rules/SGFParser.java
src/main/java/featurecat/lizzie/rules/Stone.java
src/main/java/featurecat/lizzie/rules/Zobrist.java
src/test/java/common/Util.java
src/test/java/featurecat/lizzie/analysis/MoveDataTest.java
src/test/java/featurecat/lizzie/rules/SGFParserTest.java

`mvn compile` now automatically reformats the entire codebase. They are also pugins available for Eclipse & IntelliJ, see https://github.com/google/google-java-format.
This PR is best reviewed commit by commit given that the 2nd one is an auto generated diff. The 3rd commit does some very light refactoring to make the code fit nicely in the 100 line width limit enforced by the formatter.

Setup automatic code formatter using the Google Java Style

---

pom.xml
src/main/java/featurecat/lizzie/Lizzie.java
src/main/java/featurecat/lizzie/analysis/Leelaz.java
src/main/java/featurecat/lizzie/gui/BoardRenderer.java
src/main/java/featurecat/lizzie/gui/LizzieFrame.java

Fixed some merge issues

---

src/main/java/featurecat/lizzie/Config.java
src/main/java/featurecat/lizzie/gui/BoardRenderer.java
src/main/java/featurecat/lizzie/gui/LizzieFrame.java
src/main/java/featurecat/lizzie/rules/Board.java
src/main/java/featurecat/lizzie/rules/BoardData.java
src/main/java/featurecat/lizzie/rules/SGFParser.java

Closes: #308 
Base on: #368 
Support save the winrate etc. into the comment of Sgf (need turn on "append-winrate-to-comment" in the config.txt)
format as followings:
Move \<move number>
\<Winrate> (\<Last Move Rate Difference>)
(\<Weight name> / \<Playouts>)
for example:
W[dd]C[Move 2
53.5% (-0.1%)
(elf_v1 / 18k playouts)
other comments];

next: Allow write winrate etc. to the comment of the sgf by append-winrate-to-comment

---

src/main/java/featurecat/lizzie/gui/Input.java
src/main/java/featurecat/lizzie/gui/LizzieFrame.java
src/main/java/featurecat/lizzie/gui/WinrateGraph.java
src/main/java/featurecat/lizzie/rules/Board.java

#351 
I'm trying to display blunder bar in the winrate graph.
* 1. Add new option 'show-winrate-blunder-bar' in the config.txt to turn on blunder bar, default is turn off.
* 2. Can specify the minimum width of the blunder bar by the option 'minimum-winrate-blunder-bar-width' in the config.txt, default is 3.
* 3. Considering that the winrate change should be mostly below 50%, an option is added to weighted display the height of the bar, that is, the change below 50% increases the display height, and the above 50% reduces the height. Currently only a simple weighted, the winrate change below 50% uses 75% of the display area, the above uses 25% of the display area. The default is off
turn off -> turn on
Adjusted for the green of the winrate graph should always be on top:
* 4. Due to the …

next: Display blunder bar in the winrate graph

---

src/main/java/featurecat/lizzie/gui/LizzieFrame.java

Right now, whenever a branch is being shown and pondering is off, only going to an unvisited intersection will bring back the move statistics, not moving the cursor away from the board.

Repaint board when mouse leaves it showing branch.

---

src/main/java/featurecat/lizzie/Config.java
src/main/java/featurecat/lizzie/gui/VariationTree.java
src/main/java/featurecat/lizzie/rules/Board.java
src/main/java/featurecat/lizzie/rules/BoardData.java
src/main/java/featurecat/lizzie/rules/BoardHistoryList.java
src/main/java/featurecat/lizzie/rules/BoardHistoryNode.java
src/main/java/featurecat/lizzie/rules/SGFParser.java

1. Support more sgf variation format and enhance the variation display.
2. New move number in the branch, the option is 'new-move-number-in-branch', default on.

next: Enhance the variation read and display

---

src/main/java/featurecat/lizzie/gui/BoardRenderer.java

Because integer division rounds towards zero rather than negative infinity, the code currently maps some points off the board to coordinates on the first row and/or column.

Stricter screen-to-coordinates conversion.

---

.travis.yml

Travis has been broken for a while. Using the correct image to enable Java 8 from https://docs.travis-ci.com/user/reference/osx/#jdk-and-os-x

Reconfigured Travis

---

README.md

The build status otherwise linked to the image itself. Now it is quicker to go to see what has happened in Travis.

Make build status a link

---

src/main/java/featurecat/lizzie/gui/LizzieFrame.java

OpenSans font was used for Japanese text.

Fix #490 (Japanese font problem)

---

src/main/java/featurecat/lizzie/gui/BoardRenderer.java

In BoardRenderer.drawEstimateRectKata, make a new overlay image and write everything to it before swapping it over, hopefully atomically, into cachedEsitmateRectImage. This should prevent the flickering and occasional corruption described in #569.

Don't modify cachedEsitmateRectImage incrementally; should fix #569.

---

src/main/java/featurecat/lizzie/gui/WinrateGraph.java

Removing the duplicated 95% factor which made the scoreMean graph and the current scoreMean text in wrong position.

Removing the duplicated 95% factor for scoreMean info

---

pom.xml

To address the issue in #522 and thank @scw1109 's investigation.
My env: 
Apache Maven 3.6.1
JDK: openjdk 12.0.1 2019-04-16
OS name: "mac os x", version: "10.14.5", arch: "x86_64", family: "mac"

Fix appbundler maven plugin dependency

---

src/main/java/featurecat/lizzie/gui/Menu.java

The communication breakdown with the engine as mentioned in https://github.com/featurecat/lizzie/issues/580#issuecomment-515532209 and https://github.com/featurecat/lizzie/pull/577#issuecomment-518887275 was ultimately due to a simple null-pointer exception.

Add null check

---

src/main/java/featurecat/lizzie/gui/BoardRenderer.java

I notice if start with no coordinates,the board marginWidth  will change at first,by Changeing BoarderRenderer.emptyName to true can fix it.

Change BoarderRenderer.emptyName to true

---

src/main/java/featurecat/lizzie/rules/SGFParser.java

[20191005-9454.zip](https://github.com/featurecat/lizzie/files/3701223/20191005-9454.zip)
Its a Sgf from QQ group, displayed as garbled character beacuse of wrong encoding detecting.
this is right:

Fix an encoding issue

---

src/main/java/featurecat/lizzie/gui/BoardRenderer.java

I think it is not necessary to scan every coordinates on board,and there's some formatte differences,i dont know how to make it same.

Improve the way of display suggestions moves

---

src/main/java/featurecat/lizzie/gui/BasicInfoPane.java
src/main/java/featurecat/lizzie/gui/BoardRenderer.java
src/main/java/featurecat/lizzie/gui/ConfigDialog.java
src/main/java/featurecat/lizzie/gui/LizzieFrame.java
src/main/java/featurecat/lizzie/gui/VariationTree.java
src/main/java/featurecat/lizzie/gui/WinrateGraph.java
src/main/java/featurecat/lizzie/gui/WinratePane.java
src/main/resources/l10n/DisplayStrings.properties
src/main/resources/l10n/DisplayStrings_zh_CN.properties

1. Allow user turn on/off the border
2. The board border is no longer supported, add another option if needed

Fixed: Allow user turn on/off the border and the board border is no longer supported

---

src/main/java/featurecat/lizzie/gui/ConfigDialog.java
src/main/java/featurecat/lizzie/gui/GtpConsolePane.java

I'm not sure whether this is a correct fix for #616. This PR also fixes another problem that is reported in the comments to #616: an empty GTP console (gray rectangle) is displayed even if I write `"print-comms": false` in config.txt.

Avoid empty config dialog and empty GTP console (#616)

---

src/main/java/featurecat/lizzie/analysis/Leelaz.java
src/main/java/featurecat/lizzie/rules/Board.java

This patch may fix #707 (score/win-rate flips) if it is due to a race condition as @lightvector guessed in https://github.com/lightvector/KataGo/issues/231 . I cannot check it by myself since I cannot reproduce the issue.
Lizzie already skips `parseInfo()` unless the ID of the last-received GTP response is equal to that of the last-sent GTP command in Leelaz.java. But there may be a small chance that `parseInfo()` is called between `history.next()` and `Lizzie.leelaz.playMove()` in Board.java, for example.

Maybe fix #707 (score/win-rate flips)

---

src/main/java/featurecat/lizzie/analysis/Leelaz.java

This will be useful for diagnosis of engine troubles by beginners (ref. #756).

Record startup log for #756 even when printCommunication is not set

---

src/main/java/featurecat/lizzie/analysis/Leelaz.java

ref. https://github.com/featurecat/lizzie/issues/752#issuecomment-697381196
Summary:
Fox SGF has many nodes (AI's principal variation for every move). When Lizzie reads it, more than 5000 GTP commands are sent to the engine successively. Then the pipe is stalled and Lizzie falls into a deadlock. For avoiding the deadlock, this PR introduces a writer thread so that the UI thread is not blocked even when the pipe is stalled.
Thanks to lightvector for his helpful review.

Fix #752 (deadlock by Fox SGF)

---

src/main/java/featurecat/lizzie/analysis/Leelaz.java
src/main/java/featurecat/lizzie/rules/SGFParser.java

ref. https://github.com/featurecat/lizzie/issues/752#issuecomment-695796094
Summary:
Lizzie sends play/undo commands to the engine even when it builds only internal game tree. Besides #752, this makes loading of large SGF too slow. The present PR stops these useless play/undo in SGF loading. Though this PR is not a "fix" of #752, it may be useful as acceleration of loading.

Accelerate loading of large SGF

---

src/main/java/featurecat/lizzie/analysis/Leelaz.java

Lizzie can freeze in switchEngine if the engine does not close its pipe after the GTP command "quit" for some reason. I noticed this when I tried a fake engine for experiments. I'm afraid this may occur when users write their scripts for cloud engines.
Here is a simple example of an engine command (for Linux). This engine works. But Lizzie freezes when the engine is switched to another one.
~~~
sh -c "cat | ./leelaz -g -w network.gz"
~~~
Anyway, infinite loop with no response is a bad idea. So this patch introduces `MAX_TRIALS` to avoid it.

Avoid infinite loop in switchEngine

---

src/main/java/featurecat/lizzie/analysis/Leelaz.java
src/main/java/featurecat/lizzie/gui/LizzieFrame.java
src/main/java/featurecat/lizzie/gui/LizzieMain.java
src/main/java/featurecat/lizzie/gui/MainFrame.java

Many many users are confused by the misleading message "Engine is loading...". It will be better to show an error dialog immediately when Lizzie failed to start the engine, at least.

Show error dialog for typical engine troubles

---

src/main/java/featurecat/lizzie/rules/GIBParser.java

`line.indexOf("GONGJE:") + 7` is always `> 0` so previously if-branch was always taken.

Fix parsing GAMEINFOMAIN when GONGJE is missing

---

src/main/java/featurecat/lizzie/Lizzie.java
src/main/java/featurecat/lizzie/gui/ConfigDialog.java

Fix #745. I also added a message dialog before the silent exit. (I'm not sure why this `exit` is needed after the initial configuration.)

Fix #745 (NPE after initial config)

---

src/main/java/featurecat/lizzie/analysis/Leelaz.java

The free handicap feature in #554 is reported to be problematic (#682, #734). So how about reverting it until someone will reimplement it in a better way?

Revert free handicap for KataGo (ref. #554, #682, #734)

---

src/main/java/featurecat/lizzie/gui/WinrateGraph.java

This PR fixes #732 and additional issues (mouse click, score curve) on the winrate graph when dynamic-winrate-graph-width (#384) is enabled.

Fix #732 etc. (dynamic-winrate-graph-width)

---

src/main/java/featurecat/lizzie/gui/LizzieFrame.java
src/main/java/featurecat/lizzie/gui/WinrateGraph.java

Fix #727
(notes)
In Lizzie, negative winrates are internally used for "no data" (e.g. place() in Board.java and getWinrateStats() in Leelaz.java). So `wr = 100 - lastWr;` was necessary in the initial version of WinrateGraph.java (82357ee). It seems needless after 570ac36 as it is inside `if (playouts > 0) {`.

Fix #727 (winrate graph for LCB)

---

src/main/java/featurecat/lizzie/gui/LizzieFrame.java
src/main/java/featurecat/lizzie/gui/WinratePane.java

This patch simply hides invalid scoreMean and scoreStdev as a quick fix of #729. Of course it is better to show saved values of them instead if we have enough motivation...

Fix #729 (scoreMean & scoreStdev)

---

pom.xml
src/main/java/featurecat/lizzie/Lizzie.java

The version number in pom.xml and Lizzie.java wasn't bumped from 0.7.2 when 0.7.3 was released, so this small PR fixes that.

bump version to 0.7.3

---

src/main/java/featurecat/lizzie/analysis/Leelaz.java

How about showing GTP console during initial tuning of KataGo to avoid long no-response?
(cf. https://github.com/featurecat/lizzie/issues/633#issuecomment-573415262)

Show GTP console during initial tuning of KataGo

---

src/main/java/featurecat/lizzie/rules/Board.java

`Board.saveBackRouting` is supposed to walk the list of `BoardHistoryNodes` from
the current position to the top of the tree, and at every node, set the
`fromBackChildren` of the previous `BoardHistoryNode` to the variation index
of the current node. However, due to a bug in `saveBackRouting`, half of the
nodes were being skipped in the process.
The effect of this is that when switching between different engines, the board
state could jump to a variation the user wasn't looking at previously. By
properly stepping through every node during `saveBackRouting`, switching between
engines always properly preserves the current variation.

Fix saveBackRouting skipping nodes

---

src/main/java/featurecat/lizzie/gui/ToolBar.java

If I click "Analyze" button in the toolbar when "Pondering on" is displayed, this text is not updated to "Pondering off" until I move the mouse cursor into the main board.

Fix: "Pondering on/off" was not updated by Analyze button

---

src/main/java/featurecat/lizzie/gui/GtpConsolePane.java

It is annoying that `mvn package` modifies indents of GtpConsolePane.java every time. I will be glad if @featurecat merges this PR into master soon for comfortable developments.

Correct inconsistent indents
