featurecat/lizzie

src/wagner/stephanie/lizzie/analysis/Leelaz.java
Yesterday I launched the application on my home laptop and everything worked fine.
During lunch break I tried the same at work but had a NullPointerException.
So, I fixed the NPE, and tested, it works fine now.
This is actually my first github commit ever.
So I do hope I followed procedure correctly.
=> fixes NPE.

src/wagner/stephanie/lizzie/analysis/Leelaz.java
I'm not sure why `leelaz` sent me an empty line, but we shouldn't barf on it.
=> Fix StringIndexOutOfBoundsException

src/wagner/stephanie/lizzie/Config.java, src/wagner/stephanie/lizzie/gui/BoardRenderer.java, src/wagner/stephanie/lizzie/gui/Input.java, src/wagner/stephanie/lizzie/gui/LizzieFrame.java
=> Toggle variation display

src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java, src/main/java/wagner/stephanie/lizzie/rules/SGFParser.java
After loading an SGF file, display the names of the players in the title bar.
=> Display player names in title

src/main/java/wagner/stephanie/lizzie/gui/BoardRenderer.java
=> Y coordinates go from bottom to top per convention

src/main/java/wagner/stephanie/lizzie/analysis/Leelaz.java
=> Don't respond to obsolete ponder output

src/main/java/wagner/stephanie/lizzie/gui/WinrateGraph.java
=> Fix winrate graph

src/main/java/wagner/stephanie/lizzie/Config.java, src/main/java/wagner/stephanie/lizzie/analysis/Leelaz.java
As I [suggested](https://github.com/featurecat/lizzie/issues/64#issuecomment-383171824) in #64. Off by default.
=> Flag in lizzie-properties to print communications with leelaz

src/main/java/wagner/stephanie/lizzie/Config.java, src/main/java/wagner/stephanie/lizzie/gui/BoardRenderer.java
I know you asked for a feature freeze :/ but this is two lines of code and I am sad that I have to always keep making this change in my local code. Your call!
=> Option to always display win rate from Black's perspective

src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java
Don't allow main window resize to (0,0)
=> Minimum size for main window

src/main/java/wagner/stephanie/lizzie/gui/BoardRenderer.java
=> Fixes exception when stepping past a pass move.

src/main/java/wagner/stephanie/lizzie/gui/Input.java
=> Page-up and page-down moves back and forward 10 moves at the time

src/main/java/wagner/stephanie/lizzie/gui/Input.java
=> merged commit into wrong branch

src/main/java/wagner/stephanie/lizzie/analysis/Leelaz.java, src/main/java/wagner/stephanie/lizzie/analysis/LeelazListener.java, src/main/java/wagner/stephanie/lizzie/gui/Input.java, src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java, src/main/java/wagner/stephanie/lizzie/rules/Board.java, src/main/resources/l10n/DisplayStrings.properties
Trigger auto-analysis by hitting 'a'. Starts from current position, stop with a, stops when it reaches end of game.
=> Add simple auto-analysis mode. Hit a to start.

src/main/java/wagner/stephanie/lizzie/gui/BoardRenderer.java
As mentioned in #119, this has already been merged on master, but we need it in next as well.
=> Fixes exception when stepping past a pass move

src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java, src/main/java/wagner/stephanie/lizzie/gui/WinrateGraph.java
These commits fix trivial bugs of #187 (clickable winrate graph).
=> Fix trivial bugs of #187 (clickable winrate graph)

src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java, src/main/java/wagner/stephanie/lizzie/rules/GIBParser.java
Supports players names, komi, moves, pass and handicap stones.
=> Support for gib file format used by Tygem

src/main/java/wagner/stephanie/lizzie/gui/Input.java, src/main/java/wagner/stephanie/lizzie/rules/Board.java
I want to erase a branch quickly after playing a variation with "," key
(#159 Hotkey to play the displayed variation).
=> Shift-Del to delete current branch

src/main/java/wagner/stephanie/lizzie/gui/Input.java, src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java, src/main/java/wagner/stephanie/lizzie/gui/WinrateGraph.java
I noticed that the mouse hover action on the winrate graph is annoying.
Using mouse drag is simpler and comfortable, isn't it?
=> Support mouse drag instead of mouse hover on winrate graph

src/main/java/wagner/stephanie/lizzie/gui/BoardRenderer.java, src/main/java/wagner/stephanie/lizzie/gui/Input.java, src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java
I feel that it is consistent to play "leelaz's suggestion" by "," key in both cases.
* Play the displayed variation (#159), or...
* Play the best move if no variation is displayed (this patch).
Both will be useful for examining leelaz's suggestion deeper.
=> Play the best move by "," key if no variation is shown

src/main/java/wagner/stephanie/lizzie/Config.java, src/main/java/wagner/stephanie/lizzie/analysis/Leelaz.java, src/main/java/wagner/stephanie/lizzie/analysis/MoveData.java, src/main/java/wagner/stephanie/lizzie/gui/Input.java, src/main/java/wagner/stephanie/lizzie/gui/LizzieFrame.java, src/main/java/wagner/stephanie/lizzie/rules/Board.java
Took a while because of a bit of back and forth on LZ (plus I've been a bit busy), but I think we're finally there. Now works with standard LZ (not yet released, so only next branch of LZ).
=> Support for new leela zero GTP format. 

src/main/resources/l10n/DisplayStrings_zh_CN.properties
Updated the translations according to the latest language files.
=> Updated chinese translations

src/main/java/featurecat/lizzie/analysis/Leelaz.java, src/main/java/featurecat/lizzie/gui/Input.java
This seems to work for me.
The number after "=" in leelaz output is ok.
It is managed correctly in the code by @bittsitt.
I am looking forward to Lizzie 0.5.
=> Fix #254 (Enter key issue)

src/main/java/featurecat/lizzie/analysis/Branch.java
It looks that @aerisnju fixed the issue #249 already in #252.
This patch adds similar check in variation for safety.
=> Check pass in variation. Maybe fix #249

src/main/java/featurecat/lizzie/Config.java, src/main/java/featurecat/lizzie/analysis/Leelaz.java
1. Restore the leela zero & weight file check;
2. Change config defaul value:
ui.put("only-last-move-number", 0);
ui.put("append-winrate-to-comment", false);
=> bugfix: Restore leelaz check & change config default value

src/main/resources/l10n/DisplayStrings_ja_JP.properties
Hello.
I created a localization file for the Japanese language.
Please merge this file if you like.
=> Added Japanese localization translations

src/main/java/featurecat/lizzie/rules/SGFParser.java
=> Process escape char in the comment of the sgf

src/main/java/featurecat/lizzie/gui/LizzieFrame.java
This commit fixes the exception reported by @seopsx in #328.
=> Fix NPE from getLocationOnScreen_NoTreeLock

src/main/java/featurecat/lizzie/rules/SGFParser.java
I added SZ property in the output SGF to support board size 9 or 13.
=> Added SZ property in SGF

src/main/java/featurecat/lizzie/Config.java, src/main/java/featurecat/lizzie/analysis/Branch.java, src/main/java/featurecat/lizzie/analysis/Leelaz.java, src/main/java/featurecat/lizzie/gui/BoardRenderer.java, src/main/java/featurecat/lizzie/rules/Board.java, src/main/java/featurecat/lizzie/rules/BoardHistoryList.java, src/main/java/featurecat/lizzie/rules/Zobrist.java
Support more board size (>=2 if possible).
=> next: Support more board size

src/main/java/featurecat/lizzie/gui/LizzieFrame.java
Show the visits/second in the title bar:
=> next: Show the visits/second in the title bar

src/main/java/featurecat/lizzie/Config.java, src/main/java/featurecat/lizzie/gui/LizzieFrame.java
Save/Restore the Window and Board Position in the persist
=> next: Save/Restore  the Window and Board Position in the persist

src/main/java/featurecat/lizzie/gui/LizzieFrame.java
=> Revert "Fix NPE from getLocationOnScreen_NoTreeLock"

README.md
Based on my experience today setting Lizzie up I've updated the README with information to new comers.
=> Updated readme with more getting started info

src/main/java/featurecat/lizzie/Config.java, src/main/java/featurecat/lizzie/Lizzie.java, src/main/java/featurecat/lizzie/analysis/Leelaz.java, src/main/java/featurecat/lizzie/gui/BoardRenderer.java, src/main/java/featurecat/lizzie/gui/LizzieFrame.java, src/main/java/featurecat/lizzie/rules/Board.java, src/main/java/featurecat/lizzie/rules/BoardData.java, src/main/java/featurecat/lizzie/rules/SGFParser.java, src/main/java/featurecat/lizzie/theme/Theme.java
I'm preparing a couple of PRs and it's very annoying that the `com.coveo.fmt-maven-plugin` that was added to Lizzie in late October keeps modifying these 9 files every time the project is built, which messes up all the diffs.
Presumably if that format plugin is installed, it's expected for the checked-in source to conform to it. So here are those 9 changes applied, so all future diffs will be nice and clean :)
=> Apply changes made by fmt-maven-plugin

src/main/java/featurecat/lizzie/rules/SGFParser.java
Fixed Sgf Pass for More Board Size
=> next: Fixed Sgf Pass for More Board Size

src/main/java/featurecat/lizzie/analysis/EngineManager.java, src/main/java/featurecat/lizzie/analysis/Leelaz.java, src/main/java/featurecat/lizzie/gui/ConfigDialog.java
Refresh the engine info when change in the ConfigDialog.
=> next: Refresh the engine info when change in the ConfigDialog

src/main/java/featurecat/lizzie/Lizzie.java, src/main/java/featurecat/lizzie/analysis/Leelaz.java, src/main/java/featurecat/lizzie/gui/ConfigDialog.java, src/main/java/featurecat/lizzie/rules/SGFParser.java, src/main/java/featurecat/lizzie/util/EncodingDetector.java, src/main/resources/l10n/DisplayStrings.properties, src/main/resources/l10n/DisplayStrings_es.properties, src/main/resources/l10n/DisplayStrings_ko.properties, src/main/resources/l10n/DisplayStrings_pl_PL.properties, src/main/resources/l10n/DisplayStrings_ru_RU.properties, src/main/resources/l10n/DisplayStrings_zh_CN.properties
1. Sgf parse: ignore some sgf missing the ; in the beginning;
2. Fixed engine issue: merged the PR #541
3. Change some description to reduce the width of the title.
=> Fix some merge issues and change some description

src/main/java/featurecat/lizzie/analysis/Leelaz.java, src/main/java/featurecat/lizzie/util/Utils.java
=> Fixed the command quote issue

src/main/java/featurecat/lizzie/analysis/Leelaz.java
=> Send the komi when  start engine

src/main/java/featurecat/lizzie/gui/BoardPane.java, src/main/java/featurecat/lizzie/gui/Input.java, src/main/java/featurecat/lizzie/gui/LizzieFrame.java, src/main/java/featurecat/lizzie/gui/LizzieMain.java, src/main/java/featurecat/lizzie/gui/MainFrame.java, src/main/java/featurecat/lizzie/util/Utils.java, src/main/resources/l10n/DisplayStrings.properties, src/main/resources/l10n/DisplayStrings_zh_CN.properties
Support save the board image and branch gif
1. Press Alt+S to save the board as image
2. Press Alt+R to save the branch as gif when mouse over the suggestion move
=> next: Support save the board image and branch gif

src/main/java/featurecat/lizzie/gui/LizzieMain.java, src/main/java/featurecat/lizzie/util/Utils.java
=> next: Support the macOS dock icon

src/main/java/featurecat/lizzie/gui/LizzieLayout.java, src/main/java/featurecat/lizzie/gui/LizzieMain.java
The Lizzie Layout supports the JToolBar.
=> Next: The Lizzie Layout supports the JToolBar

src/main/java/featurecat/lizzie/gui/CommentPane.java, src/main/java/featurecat/lizzie/gui/LizzieFrame.java, src/main/java/featurecat/lizzie/gui/LizzieLayout.java, src/main/java/featurecat/lizzie/gui/LizzieMain.java, src/main/java/featurecat/lizzie/gui/LizziePane.java, src/main/java/featurecat/lizzie/gui/MainFrame.java, src/main/java/featurecat/lizzie/gui/ToolBar.java
=> Fixed the toolbar issue

src/main/java/featurecat/lizzie/analysis/Branch.java, src/main/java/featurecat/lizzie/gui/BoardRenderer.java, src/main/java/featurecat/lizzie/gui/LizzieLayout.java, src/main/java/featurecat/lizzie/gui/LizzieMain.java
1. Fixed the pondering string position;
2. Fixed the branch display issue.
=> Fixed the pondering and branch issue

src/main/java/featurecat/lizzie/Config.java, src/main/java/featurecat/lizzie/gui/LizzieFrame.java, src/main/java/featurecat/lizzie/gui/LizzieMain.java, src/main/java/featurecat/lizzie/gui/MainFrame.java, src/main/java/featurecat/lizzie/gui/ToolBar.java, src/main/java/featurecat/lizzie/util/WindowPosition.java
Save & restore the toolbar position.
=> next: Save & restore the toolbar position

src/main/java/featurecat/lizzie/Config.java, src/main/java/featurecat/lizzie/gui/BoardPane.java, src/main/java/featurecat/lizzie/gui/BoardRenderer.java, src/main/java/featurecat/lizzie/gui/LizzieLayout.java, src/main/java/featurecat/lizzie/gui/Menu.java, src/main/java/featurecat/lizzie/gui/SubBoardPane.java, src/main/resources/l10n/DisplayStrings.properties, src/main/resources/l10n/DisplayStrings_zh_CN.properties
=> Display name at the bottom of the board

src/main/java/featurecat/lizzie/analysis/Branch.java, src/main/java/featurecat/lizzie/analysis/Leelaz.java, src/main/java/featurecat/lizzie/gui/BoardRenderer.java, src/main/java/featurecat/lizzie/rules/Board.java, src/main/java/featurecat/lizzie/rules/BoardData.java, src/main/java/featurecat/lizzie/rules/BoardHistoryList.java, src/main/java/featurecat/lizzie/rules/SGFParser.java, src/main/java/featurecat/lizzie/util/Utils.java
Support read and save the scoreMean for the sgf
=> next: Support read and save the scoreMean for the sgf

src/main/java/featurecat/lizzie/gui/BasicInfoPane.java, src/main/java/featurecat/lizzie/gui/GameInfoDialog.java
Show the komi in the basic pane
=> next: Show the komi in the basic pane

src/main/java/featurecat/lizzie/gui/OnlineDialog.java
Fixed the end game comment issue.
=> Fixed the end game comment issue

src/main/java/featurecat/lizzie/gui/OnlineDialog.java
Fixed the color for the online
=> Fixed the color for the online

src/main/java/featurecat/lizzie/gui/OnlineDialog.java
=> Fixed the online komi issue

README.md
=> Add the Wiki link.

src/main/java/featurecat/lizzie/analysis/Leelaz.java, src/main/java/featurecat/lizzie/gui/LizzieFrame.java, src/main/java/featurecat/lizzie/gui/LizzieMain.java, src/main/java/featurecat/lizzie/gui/RightClickMenu.java
I think when force analyzing it should avoid for both black and white. and fix some useless popupmenu, when using katago
=> Avoid for both white and black

src/main/java/featurecat/lizzie/gui/CountResults.java
=> Ajust countResult drawing

src/main/java/featurecat/lizzie/gui/MainFrame.java
Like title, just an small fix.
=> Fix cannot delect Sgf file with capital extendsion ("*.SGF")

src/main/java/featurecat/lizzie/rules/SGFParser.java
This PR imports https://github.com/sanderland/katrain/issues/177#issuecomment-683112312 to Lizzie for #755.
=> Import komi fix for Fox SGF from KaTrain (ref. #755)

src/main/java/featurecat/lizzie/analysis/GameInfo.java
=> Fix obsolete "Leela Zero" for the default player name

src/main/java/featurecat/lizzie/gui/WinratePane.java
@siasio, your screenshots helped me much! The red dot above the winrate bar is the key of this issue.
=> Fix #701 (wrong winrate in WinratePane)

src/main/java/featurecat/lizzie/analysis/EngineManager.java, src/main/java/featurecat/lizzie/analysis/Leelaz.java, src/main/java/featurecat/lizzie/gui/BoardRenderer.java, src/main/java/featurecat/lizzie/rules/BoardData.java
Changing komi should cause Lizzie to regenerate analysis.
Try to fix the issue #643
=> next: Changing komi should cause Lizzie to regenerate analysis
